### ISSUE TITLE
First-time typing

### ISSUE THREAD

**Issue by LukasBudach** [hpi-swa-teaching/SWT18-Project-04#25]
Upon typing initializeCompletionController for the first time using our correction, it is not recommended in any way (even if menu is extended).
It will be recommended after having typed it once though.

**Comment by LukasBudach** [comment]
May be something to look at for @arne-z or @Portoso

**Comment by Portoso** [comment]
I tried it and it wasn't recommended even after typing it once.
The problem is, that the OCompletionTable is capped to 40 words per starting letter,
so initializeCompletionController isnt in the OCompletionTable.
That means the OCompletion has the same problem, what could make it pretty hard to fix.

**Comment by LukasBudach** [comment]
This is kind of fixed due to our fix on updating the table.
Typing Classes/Methods for the first time ever using our tool may still cause them to not be recognized, but they will afterwards and these cases will get less and less the longer our tool is used.
